Update README.md
braintree/braintree-android-drop-in pull request #492
Opened 2024-12-11 23:52 UTC by stechiu

### Summary of changes

 - Updated README on SDK deprecation

 ### Checklist

 - [ ] Added a changelog entry

### Authors
> List GitHub usernames for everyone who contributed to this pull request.

- @stechiu

2024-12-12 00:12 UTC, saperi22 commented
Consider updating the Versions section of the README.

2024-12-12 00:21 UTC, saperi22 requested changes

2024-12-12 00:21 UTC, saperi22 commented on README.md
> +**The Android Drop-In SDK is currently inactive and will be unsupported by November 2025**. As of December 2024, the Android Drop-In SDK is inactive. No additional features will be added with the exc
```suggestion
**The Android Drop-In SDK is currently inactive and will be unsupported by November 2025**. As of December 2024, the Android Drop-In SDK is inactive. No additional features will be added with the exception of security updates. As an alternative, we recommend using the ![Braintree SDK](https://github.com/braintree/braintree_android) for unbranded checkout.
```

2024-12-12 00:21 UTC, saperi22 commented on README.md
> +This SDK abides by our Client SDK Deprecation Policy. For more information on the potential statuses of an SDK check our ![developer docs](https://developer.paypal.com/braintree/docs/guides/client-sd
```suggestion
This SDK abides by our Client SDK Deprecation Policy. For more information on the potential statuses of an SDK check our ![developer docs](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy/android/v5).
```

2024-12-12 00:21 UTC, stechiu commented on README.md
> +**The Android Drop-In SDK is currently inactive and will be unsupported by November 2025**. As of December 2024, the Android Drop-In SDK is inactive. No additional features will be added with the exc
thanks for catching that!

2024-12-12 00:31 UTC, saperi22 approved these changes

2024-12-17 17:18 UTC, closed without merging

2024-12-17 17:18 UTC, stechiu commented
Closing for now until team comes to conclusion about communication timelines